### ISSUE TITLE
Error: System "harmony-simple" not found

### ISSUE THREAD

**Issue by jnc-nj** [Shirakumo/harmony#1]
It seems that quicklisp can't find the system, is there an alternative way to install?

**Comment by Shinmera** [comment]
It's not yet in Quicklisp. If you want to try it out already, clone it, [flow](https://github.com/Shinmera/flow), and [cl-mixed](https://github.com/Shirakumo/cl-mixed) to local-projects.

**Comment by jnc-nj** [comment]
It's up now! And i've got to say, this is probably the easiest to use sound library for lisp i've had the pleasure of using thus far :)

**Comment by Shinmera** [comment]
Glad to hear! It still needs some work though, mostly to add support for source formats other than mp3. Not sure when I'll get the time to work on that.
