### ISSUE TITLE
Unattached Buffers in Source/Drain Leads to Null-Deref

### ISSUE THREAD

**Issue by gregcman** [Shirakumo/harmony#10]
This is SBCL 1.4.5.3-cd28228, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :harmony-simple)
To load "harmony-simple":
  Load 1 ASDF system:
    harmony-simple
; Loading "harmony-simple"
....
(:HARMONY-SIMPLE)
* (harmony-simple:initialize)

#<SB-THREAD:THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {10030E59B3}>
* (harmony-simple:play #P"/home/imac/Music/Louis The Child ft. K.Flay - It's Strange [Premiere] (FIFA 16 Soundtrack) -  128kbps.mp3" :sfx)

debugger invoked on a SB-KERNEL:NO-NATIVE-NAMESTRING-ERROR in thread
#<THREAD "main thread" RUNNING {10005E85B3}>:
  The pathname
  #P"/home/imac/Music/Louis The Child ft. K.Flay - It's Strange [Premiere] (FIFA 16 Soundtrack) -  128kbps.mp3"
  does not have a native namestring because
  of the :NAME component #<SB-IMPL::PATTERN "Louis The Child ft. K.Flay - It's Strange "
                                            (:CHARACTER-SET . "Premiere")
                                            " (FIFA 16 Soundtrack) -  128kbps">.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(SB-KERNEL:NO-NATIVE-NAMESTRING-ERROR #P"/home/imac/Music/Louis The Child ft. K.Flay - It's Strange [Premiere] (FIFA 16 Soundtrack) -  128kbps.mp3" "of the ~S component ~S." :NAME #<SB-IMPL::PATTERN ("Louis The Child ft. K.Flay - It's Strange " (:CHARACTER-SET . "Premiere") " (FIFA 16 Soundtrack) -  128kbps")>)
0] 0

* (harmony-simple:play #P"/home/imac/Music/6PQv-Adele - Hello.mp3" :sfx)

#<HARMONY-MP3:MP3-SOURCE  playing>
* CORRUPTION WARNING in SBCL pid 4975(tid 0x7ffff5b0f700):
Memory fault at (nil) (pc=0x7ffff66df1b2, sp=0x7ffff5b0e180)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.

debugger invoked on a SB-SYS:MEMORY-FAULT-ERROR in thread
#<THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {10030E59B3}>:
  Unhandled memory fault at #x0.

**Comment by terminal625** [comment]
Both of these issues seem to be independent of each other?

**Comment by Shinmera** [comment]
For the first one you're not understanding namestrings correctly, which has nothing to do with Harmony. Angle brackets mean something special and need to be escaped in SBCL. If you're not sure about the namestring syntax, use `uiop:parse-native-namestring`.

For the second one I don't know what's going on. Can  you get a backtrace at least?

**Comment by terminal625** [comment]
Thanks for correcting me on the namestring thing, sorry to waste your time with that. Here's the backtrace and example:

`CL-USER> (ql:quickload :harmony-simple)
To load "harmony-simple":
  Load 1 ASDF system:
    harmony-simple
; Loading "harmony-simple"
..................................................
[package cl-mixed-cffi]...........................
[package cl-mixed]................................
..................................................
[package closer-mop]..............................
[package closer-common-lisp]......................
[package closer-common-lisp-user].................
[package flow]....................................
[package harmony].................................
[package harmony-alsa-cffi].......................
[package harmony-alsa]............................
[package cl-mpg123-cffi]..........................
[package cl-mpg123]...............................
[package harmony-mp3].............................
[package harmony-wav].............................
[package cl-flac-cffi]............................
[package cl-flac].................................
[package harmony-flac]............................
[package harmony-simple].
(:HARMONY-SIMPLE)
CL-USER> (harmony-simple:initialize)
#<SB-THREAD:THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {1002CE59B3}>
CL-USER> (harmony-simple:play #P"/home/imac/Music/6PQv-Adele - Hello.mp3" :sfx)
#<HARMONY-MP3:MP3-SOURCE  playing>
CL-USER> `

`Unhandled memory fault at #x0.
   [Condition of type SB-SYS:MEMORY-FAULT-ERROR]

Restarts:
 0: [CONTINUE] Continue with fingers crossed.
 1: [ABORT] abort thread (#<THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {1002CE59B3}>)

Backtrace:
  0: (SB-SYS:MEMORY-FAULT-ERROR #<unused argument> #.(SB-SYS:INT-SAP #X00000000))
      Locals:
        SB-KERNEL::ADDRESS-SAP = #.(SB-SYS:INT-SAP #X00000000)
  1: ("foreign function: call_into_lisp")
      [No Locals]
  2: ("foreign function: funcall2")
      [No Locals]
  3: ("foreign function: handle_trap")
      [No Locals]
  4: ("foreign function: #x419F10")
      [No Locals]
  5: ((LAMBDA (HARMONY:SAMPLES HARMONY:SEGMENT) :IN "/home/imac/quicklisp/dists/quicklisp/software/harmony-20180711-git/source.lisp") 441 #.(SB-SYS:INT-SAP #X7FFFF0038430))
      Locals:
        HARMONY:SAMPLES = 441
        HARMONY:SEGMENT = #.(SB-SYS:INT-SAP #X7FFFF0038430)
        HARMONY:SOURCE = #<HARMONY-MP3:MP3-SOURCE  playing>
  6: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/home/imac/quicklisp/dists/quicklisp/software/cl-mixed-20180131-git/segments/virtual.lisp") #<unavailable argument> #<unavailab..
      [No Locals]
  7: ("foreign function: funcall_alien_callback")
      [No Locals]
  8: ("foreign function: callback_wrapper_trampoline")
      [No Locals]
  9: ("foreign function: #x20100687")
      [No Locals]
 10: ((:METHOD HARMONY:RUN (HARMONY:SERVER)) #<HARMONY-SIMPLE:DEFAULT-SERVER running>) [fast-method]
      Locals:
        HARMONY:DEVICE = #<HARMONY-ALSA:ALSA-DRAIN >
        HARMONY::EVALUATION-QUEUE = (T)
        SEQUENCE = #.(SB-SYS:INT-SAP #X7FFFF0000FF0)
        HARMONY:SERVER = #<HARMONY-SIMPLE:DEFAULT-SERVER running>
 11: ((LAMBDA NIL :IN HARMONY:START))
      Locals:
        HARMONY:SERVER = #<HARMONY-SIMPLE:DEFAULT-SERVER running>
 12: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
      [No Locals]
 13: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      Locals:
        SB-THREAD:THREAD = #<SB-THREAD:THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {1002CE59B3}>
      Catch-tags:
        SB-THREAD::%RETURN-FROM-THREAD
 14: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      Locals:
        SB-THREAD:THREAD = #<SB-THREAD:THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {1002CE59B3}>
 15: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
      [No Locals]
      Catch-tags:
        SB-THREAD::%ABORT-THREAD
        SB-IMPL::%END-OF-THE-WORLD
        SB-INT:TOPLEVEL-CATCHER
 16: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
      Locals:
        GOT-IT = T
        MUTEX = #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {1002CE59B3}>>
 17: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFF603ED4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
      Locals:
        FUNCTION = #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFF603ED4B}>
        SB-THREAD::GOT-IT = T
        SB-THREAD:MUTEX = #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {1002CE59B3}>>
        SB-THREAD::TIMEOUT = NIL
        SB-THREAD::VALUE = NIL
        SB-THREAD::WAITP = T
 18: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {1002CE59B3}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPEC..
      Locals:
        SB-THREAD::ARGUMENTS = NIL
        SB-THREAD::REAL-FUNCTION = #<CLOSURE (LAMBDA () :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1002CE595B}>
        SB-THREAD::SETUP-SEM = NIL
        SB-THREAD:THREAD = #<SB-THREAD:THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {1002CE59B3}>
 19: ("foreign function: call_into_lisp")
      [No Locals]
 20: ("foreign function: new_thread_trampoline")
      [No Locals]
`

**Comment by terminal625** [comment]
Ubuntu 18.04.1 LTS (Bionic Beaver)

**Comment by Shinmera** [comment]
I'm afraid that trace doesn't really help me figure out what the problem is. I'll have to see if I can somehow reproduce it. What operating system is this?

**Comment by Shinmera** [comment]
Sorry, I cannot reproduce your issue with a completely clean VM install of Ubuntu 18.04.1. There was a minor issue with it not finding libasound.so, but that should have errored way earlier. Can you try again with local copies of both cl-mixed and harmony from Git?

**Comment by terminal625** [comment]
Just installed local copies cl-mixed and harmony, was using a different version. Here is the new test and backtrace, it has more information regarding the C calls. "6PQv-Adele -Hello.mp3" is a stereo file. I also tried it with a mono mp3 with the same result. 

```
CL-USER> (ql:quickload :harmony-simple)
To load "harmony-simple":
  Load 1 ASDF system:
    harmony-simple
; Loading "harmony-simple"
..................................................
[package harmony-alsa-cffi].......................
[package harmony-alsa]............................
[package harmony-mp3].............................
[package harmony-wav].............................
[package harmony-flac]............................
[package harmony-simple].
(:HARMONY-SIMPLE)
CL-USER> (harmony-simple:initialize)
#<SB-THREAD:THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {10054759B3}>
CL-USER> (harmony-simple:play #P"/home/imac/Music/6PQv-Adele - Hello.mp3" :sfx)
#<HARMONY-MP3:MP3-SOURCE  playing>
CL-USER> 

Unhandled memory fault at #x0.
   [Condition of type SB-SYS:MEMORY-FAULT-ERROR]

Restarts:
 0: [CONTINUE] Continue with fingers crossed.
 1: [ABORT] abort thread (#<THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {10054759B3}>)

Backtrace:
  0: ("bogus stack frame")
  1: ("foreign function: #x7FFFF4F32A24")
  2: ("foreign function: mixed_buffer_from_packed_audio")
  3: ("foreign function: #x7FFFF4F3E213")
  4: ((:METHOD HARMONY:PROCESS :AROUND (HARMONY:UNPACK-SOURCE T)) #<HARMONY-MP3:MP3-SOURCE  playing> 441) [fast-method]
      Locals:
        SB-PCL::.NEXT-METHOD-CALL. = #S(SB-PCL::FAST-METHOD-CALL :FUNCTION #<FUNCTION (SB-PCL::FAST-METHOD HARMONY:PROCESS (HARMONY-MP3:MP3-SOURCE T))> :PV NIL :NEXT-METHOD-CALL NIL :ARG-INFO (2))
        HARMONY:SAMPLES = 441
        HARMONY:SOURCE = #<HARMONY-MP3:MP3-SOURCE  playing>
  5: ((LAMBDA (HARMONY:SAMPLES HARMONY:SEGMENT) :IN "/home/imac/quicklisp/local-projects/harmony/source.lisp") 441 #.(SB-SYS:INT-SAP #X7FFFF0038420))
      Locals:
        HARMONY:SAMPLES = 441
        HARMONY:SEGMENT = #.(SB-SYS:INT-SAP #X7FFFF0038420)
        HARMONY:SOURCE = #<HARMONY-MP3:MP3-SOURCE  playing>
  6: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/home/imac/quicklisp/local-projects/cl-mixed/segments/virtual.lisp") #<unavailable argument> #<unavailable argument> #<unavaila..
  7: ("foreign function: funcall_alien_callback")
  8: ("foreign function: callback_wrapper_trampoline")
  9: ("foreign function: #x20100697")
 10: ("foreign function: #x7FFFF0007D54")
 11: ("foreign function: mixed_segment_sequence_mix")
 12: (CL-MIXED-CFFI:SEGMENT-SEQUENCE-MIX 441 #.(SB-SYS:INT-SAP #X7FFFF0034750))
      Locals:
        MIXER = #.(SB-SYS:INT-SAP #X7FFFF0034750)
        SAMPLES = 441
 13: ((:METHOD HARMONY:RUN (HARMONY:SERVER)) #<HARMONY-SIMPLE:DEFAULT-SERVER running>) [fast-method]
      Locals:
        HARMONY:DEVICE = #<HARMONY-ALSA:ALSA-DRAIN >
        HARMONY::EVALUATION-QUEUE = (T)
        SEQUENCE = #.(SB-SYS:INT-SAP #X7FFFF0034750)
        HARMONY:SERVER = #<HARMONY-SIMPLE:DEFAULT-SERVER running>
 14: ((LAMBDA NIL :IN HARMONY:START))
      Locals:
        HARMONY:SERVER = #<HARMONY-SIMPLE:DEFAULT-SERVER running>
 15: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
 16: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 17: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 18: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 19: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
 20: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFEF946D4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
 21: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {10054759B3}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPEC..
 22: ("foreign function: call_into_lisp")
 23: ("foreign function: new_thread_trampoline")
```

Decoding the files beforehand and choosing one channel to play from a multi-channel mp3 seems to work. BTW, you may want to change
```(harmony-simple:play 'harmony:buffer-source :sfx :buffers *explosion*)```
to
```(harmony-simple:play 'harmony:buffer-source :sfx :buffers (list (first *explosion*)))```
in the README.md in case "explosion.mp3" is multi-channel mp3, that worked for me.

**Comment by Shinmera** [comment]
Ah- blast. I tested with the :music mixer, rather than the :sfx one. I can reproduce your issue, sorry about that.

**Comment by Shinmera** [comment]
The reason why the mono file also fails is because it automatically turns it into stereo by default. You need to explicitly select mono with `:channels 1`. 

Regardless, a memory fault is obviously bad and I need to fix this (somehow). The problem is that, since the space mixer for sfx only uses mono sources, it only ever attaches a single buffer to the source. The source then tries to decode its contents into the buffers, but one of the buffers is missing, so it dereferences a null. There's various things we could do here, and I'm not sure which is the best right away, so I'll have to think about it.

**Comment by Shinmera** [comment]
The truly astonishing thing is that this escaped me for so long.

**Comment by terminal625** [comment]
It sounds like you think you have to fix this by yourself, but this is Open Source Software, and I'm willing to devote some energy to this. Could you share some of the specifics [repositories, source files, etc...] needed for a fix? Also, how would you feel about a portable Common Lisp implementation of libmixed? That might make debugging easier, with the added benefit of portability. If you are not interested in maintaining these projects please let me know.

**Comment by Shinmera** [comment]
Well this is an issue ticket, and I don't expect people to do things for me. The problem also requires a design decision to be made, so it's not quite straight-forward. The fix is all in libmixed, unless the remixing behaviour should be customisable, which I'm currently more against than for.

As for implementing libmixed in Lisp, I initially started this mixing adventure in Lisp, but then decided to write the core loop in C because I couldn't get satisfactory performance. If you feel like you have the time to replicate all of libmixed and make it competetitive in speed, go for it.

**Comment by Shinmera** [comment]
Specifically, the behaviour that needs changing should either be in:
* `mixed_buffer_from/to_*`, to detect null pointers in the buffer array and switch the behaviour to accommodate for channel remixing.
* `source/drain_segment_start`, to automatically attach buffers to complete the buffer array.

As for how to fix it: on unpack, you can either:
* Ignore inexistent buffers, discarding samples from additional channels. For stereo to mono this would mean only using the left channel, for instance.
* Linearly interpolate all channels to the target number of buffers. For stereo to mono this would mean adding both together and dividing by two. For three to two channels it would mean mixing channel 1 and 2, and 2 and 3, and so forth. This is complicated further if you want to do the right thing for surround channel layouts and such (FL, FR, BL, BR, C, S, etc.). It is however also the less surprising thing to do.

On pack, you have similar options:
* Unmatched channels simple get set to a constant null sample. This means that for mono to stereo only the left channel plays anything.
* Again perform a linear innterpolation, but in the other direction. Same caveats and advantages apply.

If this should be customisable, a new interface to choose and configure the behaviour needs to be added to the `mixed_packed_audio` struct alongside the actual remixing functionality of course. It would take quite a bit of work, I wager.

**Comment by terminal625** [comment]
Unfortunately what seems like a simple fix seems to require a lot more effort than I expected, as I have minimal experience with: debugging C and Common Lisp simultaneously, design decisions, and libmixed. But much thanks for taking the time to try explain it to me anyway. I'm interested in this project because it is apparently the most portable high quality audio player for Common Lisp, and many of harmony's components could seemingly be separated into their own projects, for example the .wav decoder, harmony/sources, and harmony/drains. As for porting libmixed, how would you feel if harmony had another [optional] backend for mixing, like cl-mixed, but in pure common lisp? And also, would you take a pull request that uses less CLOS? [It may make porting harmony to other languages without multiple dispatch easier, as well as give minor speedups from not doing type-dispatch for methods] Again, thanks for reading this.

**Comment by Shinmera** [comment]
libmixed is too tightly integrated into almost every part of Harmony to allow it to be switched out with another backend without complicating the design tremendously. Harmony is essentially only a server component and implementation of some sources/drains on top of libmixed, so it doesn't do much on its own to begin with. That is to say if the libmixed port was ever done, adding something similar to Harmony to it would be a minor effort. Not to mention that I would gladly switch away from C, so if this was ever realised and competitive in performance I would not mind at all switching.

I don't think that the ease to rewrite it in another language is any justifiable reason at all to cripple a library. Currently CLOS is only used in minor parts in the hot loop, which I would be willing to address once it is proven to actually be a bottleneck, but no sooner.

**Comment by terminal625** [comment]
[Added null buffer discarding to libmixed](https://github.com/Shirakumo/harmony/issues/10#issuecomment-439804673) and the above examples work, but it doesn't seem like the "right" thing, since like you said the buffers could be interpolated or even there could be a customized interface. At least now it degrades gracefully instead of core dumping. Perhaps there could be some sort of callback that does something more customisable? [https://github.com/Shirakumo/libmixed/pull/4](https://github.com/Shirakumo/libmixed/pull/4)

**Comment by Shinmera** [comment]
Outdated since 2.0
