### ISSUE TITLE
issue playing more than one file on music mixer

### ISSUE THREAD

**Issue by azimut** [Shirakumo/harmony#16]
not sure if it is unsupported, a bug or something that could potentially be done with a custom segment (which I haven't read yet)

given 3 stereo mp3-sources when I resume/play them on :music they work fine individually but once I resume a 2nd or 3rd one the audio of the "old" one outputs only on 1 channel and the "new" one is hear on both channels

and as i remove (stop looping) sources 1 always gets stereo and the other 1 channel output

**Comment by Shinmera** [comment]
Sorry you're experiencing this many issues. I can't recall encountering this before and don't know why it would happen either.

Unfortunately I lack the time to work on my projects right now, so I can't say when I'll get to fix it.

**Comment by azimut** [comment]
no problem, is understandable

**Comment by azimut** [comment]
fwiw, i workaround this by doing the :music mixer mono and skipping a check on flow

**Comment by Shinmera** [comment]
Out of date for 2.0
