### ISSUE TITLE
missing location for mp3-source

### ISSUE THREAD

**Issue by azimut** [Shirakumo/harmony#17]
on the preview video https://www.youtube.com/watch?v=rMXLgQEXS8g you could access the location of a mp3 source, but that seems missing on the current code.

I could still get the location of the :sfx mixer though.

```
> (defvar *tmp* (harmony-simple:play #p"/home/user/421128__giocosound__footstep-grass-4.mp3" :sfx :paused t))
#<HARMONY-MP3:MP3-SOURCE  paused>
> (harmony-simple:location *tmp*)
```

 There is another way to do it atm?

**Comment by Shinmera** [comment]
The location of a source is on the mixer, as that defines whether you do positional audio or not.  In the standard pipeline, only the sfx and voice mixers are space mixers. https://github.com/Shirakumo/harmony/blob/master/simple/default.lisp#L30

I don't understand how your snippet is supposed to be different from what I do in the video?

**Comment by azimut** [comment]
gotcha, I see it now
