### ISSUE TITLE
Can't load mp3 file as :sfx from buffer

### ISSUE THREAD

**Issue by Boberkraft** [Shirakumo/harmony#18]
```common-lisp
(ql:quickload :harmony-simple)
(harmony-simple:initialize)
(defvar *explosion* (harmony-simple:decode #p"kick.mp3"))
(harmony-simple:play 'harmony:buffer-source :sfx :buffers *explosion*)


* debugger invoked on a SB-INT:INVALID-ARRAY-INDEX-ERROR in thread
#<THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {1003D2C393}>:
  Invalid index 1 for (SIMPLE-VECTOR
                       1), should be a non-negative integer below 1.
```
It does work in the following combinations:
- buffer-source, :music, .mp3 file
- buffer-source, :sfx, .wav file
so i think its something about decoding mp3 files

**Comment by Shinmera** [comment]
Has nothing to do with mp3, but everything with the number of channels your source has. `sfx` is a mono mixer.

**Comment by Boberkraft** [comment]
kick.mp3 is mono. Loading a second stereo file (stereo.mp3) results in the same error.
![image](https://user-images.githubusercontent.com/16669574/56167268-069c6c00-5fd8-11e9-95e2-dbe8ee3d967f.png)

**Comment by Shinmera** [comment]
What's the backtrace?

**Comment by Boberkraft** [comment]
<details><summary>Mono kick.mp3</summary>




<p>
Invalid index 1 for (SIMPLE-VECTOR 1), should be a non-negative integer below 1.
   [Condition of type SB-INT:INVALID-ARRAY-INDEX-ERROR]





Restarts:
 0: [CONTINUE] Continue with fingers crossed.
 1: [ABORT] abort thread (#<THREAD "#<DEFAULT-SERVER running> process thread." RUNNING {10041A0B93}>)

Backtrace:
  0: ((SB-IMPL::OPTIMIZED-DATA-VECTOR-REF T) #(#<CL-MIXED:BUFFER {10037E85C3}>) 1)
      Locals:
        SB-INT:INDEX = 1
        VECTOR = #(#<CL-MIXED:BUFFER {10037E85C3}>)
  1: ((:METHOD HARMONY:PROCESS (HARMONY:BUFFER-SOURCE T)) #<HARMONY:BUFFER-SOURCE  playing> 441) [fast-method]
      Locals:
        HARMONY::BUFFER = #.(SB-SYS:INT-SAP #X011D4BA0)
        HARMONY:BUFFERS = #(#<CL-MIXED:BUFFER {1004399F43}> #<CL-MIXED:BUFFER {100439A0C3}>)
        HARMONY::BYTES = 1764
        HARMONY::I = 1
        CL-MIXED:OUTPUTS = #(#<CL-MIXED:BUFFER {10037E85C3}>)
        HARMONY::POS = 0
        READ = 1764
        HARMONY:SAMPLES = 441
        HARMONY:SOURCE = #<HARMONY:BUFFER-SOURCE  playing>
  2: ((LAMBDA (HARMONY:SAMPLES HARMONY:SEGMENT) :IN "C:/Users/Bobi/quicklisp/dists/quicklisp/software/harmony-20190107-git/source.lisp") 441 #.(SB-SYS:INT-SAP #X03DBB6D0))
      Locals:
        HARMONY:SAMPLES = 441
        HARMONY:SEGMENT = #.(SB-SYS:INT-SAP #X03DBB6D0)
        HARMONY:SOURCE = #<HARMONY:BUFFER-SOURCE  playing>
  3: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "C:/Users/Bobi/quicklisp/dists/quicklisp/software/cl-mixed-20190107-git/segments/virtual.lisp") #<unavailable argument> #<unavai..
  4: ("foreign function: #x436248")
  5: ("foreign function: #x4035C8")
  6: ("foreign function: #x6A2C6734")
  7: (CL-MIXED-CFFI:SEGMENT-SEQUENCE-MIX 441 #.(SB-SYS:INT-SAP #X0127DFC0))
      Locals:
        MIXER = #.(SB-SYS:INT-SAP #X0127DFC0)
        SAMPLES = 441
  8: ((:METHOD HARMONY:RUN (HARMONY:SERVER)) #<HARMONY-SIMPLE:DEFAULT-SERVER running>) [fast-method]
      Locals:
        HARMONY:DEVICE = #<HARMONY-WASAPI:WASAPI-DRAIN >
        HARMONY::EVALUATION-QUEUE = (T)
        SEQUENCE = #.(SB-SYS:INT-SAP #X0127DFC0)
        HARMONY:SERVER = #<HARMONY-SIMPLE:DEFAULT-SERVER running>
  9: ((LAMBDA NIL :IN HARMONY:START))
      Locals:
        HARMONY:SERVER = #<HARMONY-SIMPLE:DEFAULT-SERVER running>




</p>
</details>

**Comment by Shinmera** [comment]
Okey, so the problem was guessed correctly: it decoded it to stereo. I can include a kludge fix to only use whichever number of buffers is smaller, but it's not clear that that should be allowed, and an explicit error on buffer count mismatch wouldn't be better.

**Comment by Shinmera** [comment]
When decoding, it defaults to stereo for the mp3-source. You can tell it to use mono by passing `:channels 1` to `decode`.

**Comment by Boberkraft** [comment]
Yea i was about to say that backtrace for stereo.mp3 was the same. I think that when there are 2 channels and the source have only 1, it shouldn't raise an error. For the other way around, a warning would be nice or it should just normally play the sound in mono.

**Comment by Shinmera** [comment]
There's a discussion here as to why this kind of thing is not an easy design decision:
https://github.com/Shirakumo/harmony/issues/10#issuecomment-439804673

**Comment by Shinmera** [comment]
Out of date for 2.0
