### ISSUE TITLE
Can't build today - can't find CL-MIXED?

### ISSUE THREAD

**Issue by quicklisp** [Shirakumo/harmony#19]
I get this: `Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {10008E8083}>: The name "CL-MIXED" does not designate any package.`

Log here: http://report.quicklisp.org/2020-09-02/failure-report/harmony.html#harmony

**Comment by Shinmera** [comment]
Is shirakumo/cl-mixed#7 fixed, then?

**Comment by quicklisp** [comment]
I am able to build (most of) cl-mixed now, the only failure is http://report.quicklisp.org/2020-09-02/failure-report/cl-mixed.html#cl-mixed-winmm

**Comment by Shinmera** [comment]
That should be fixed now, too. I'll get to Harmony in a bit.

**Comment by quicklisp** [comment]
This remains a build breaker for me.

**Comment by quicklisp** [comment]
Latest log: http://report.quicklisp.org/2020-09-15/failure-report/harmony.html#harmony

**Comment by Shinmera** [comment]
You must have stale sources somehow. The error points to package.lisp, which does not contain the symbol `cl-mixed`, nor the import line mentioned in the error log.

**Comment by Shinmera** [comment]
In fact all of the systems pointed to by the failure log no longer exist.

**Comment by quicklisp** [comment]
That was it, thanks - I was getting this without noticing:

```
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```

After clearing my cache, things build fine now. Thanks.

**Comment by Shinmera** [comment]
Using ``git fetch && git reset --hard origin/master`` is a safer strategy to get to the tip than pulling.
