### ISSUE TITLE
Support for other audio formats (ogg)

### ISSUE THREAD

**Issue by juszczakn** [Shirakumo/harmony#2]
Cool library. Looks like right now, it only supports mp3 through cl-mpg123.

**Comment by Shinmera** [comment]
Yes. Other formats first need suitable wrapper libraries to decode the format.

**Comment by Shinmera** [comment]
As per af561875d8c4742af8ce871d41c0808d5d7dfd35 mp3, wav, and flac are now supported. Ogg within flac should also work.
