### ISSUE TITLE
Am I doing harmony wrong ?

### ISSUE THREAD

**Issue by wmealing** [Shirakumo/harmony#20]
Gday, 

First time user, relatively new lisper.

I have quicklisp setup, i have it searching and installing.

I'm following instructions from https://shirakumo.github.io/harmony/ , and i cant install harmony-simple

I am using sbcl with todays quicklisp.

I run:

> 
> **(ql:quickload :harmony-simple)**
> 
> System "harmony-simple" not found
>    [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]
> 

This doc mentions that its version 2.0.0

Harony system says its version 2.0.0

> 
> (asdf:defsystem harmony
>   :version "2.0.0"
> 
> 

Am I doing something wrong ?

Thanks.

**Comment by Shinmera** [comment]
The documentation there is unfortunately outdated and still talks about an old version of the library. I forgot to bump the version signifier in the system and haven't had time to update the documentation yet.

The short of it is:
```
(ql:quickload :harmony)
(org.shirakumo.fraf.harmony:start (org.shirakumo.fraf.harmony:make-simple-server))
(org.shirakumo.fraf.harmony:play #p"some-file.wav")
```

You might also need to load extra cl-mixed modules to handle file formats like `cl-mixed-wav`.
