### ISSUE TITLE
Unhandled memory fault with Ogg files

### ISSUE THREAD

**Issue by AkashaP** [Shirakumo/harmony#21]
Thanks so much this library. I was having trouble with 2 second latencies with a different OpenAL bindings library and this one performs much better.

playing ogg files works but playing too many at once crashes easily.

Sample code:
```
(dotimes (x 20) (org.shirakumo.fraf.harmony:play #P"file.ogg"))
```
is giving me
`Unhandled memory fault at #x7FC862C042F0.
   [Condition of type SB-SYS:MEMORY-FAULT-ERROR]`
 
it doesn't bother me though cause i don't get this problem converting to MP3 but i thought i'd just point it out in case anyone else is trying this library.

**Comment by Shinmera** [comment]
Okey, looks like a bug in the underlying stb_vorbis library in cl-vorbis. I've pushed a fix.
