### ISSUE TITLE
pitch effect doesn't work

### ISSUE THREAD

**Issue by Gleefre** [Shirakumo/harmony#23]
Applying `mixer:pitch` effect results in loud noise instead of actual sample.
```lisp
(harmony:play #p"sample.wav" :effects '((mixer:pitch :pitch 1.5)))  ; or any other pitch except for 1.0
;; Doesn't work for other formats as well, for example .mp3
```
On a side note, it would be nice if it was possible to do `(mixer:make-pitch :pitch 1)`, i.e. pass non single-floats as arguments.

**Comment by Shinmera** [comment]
This is an issue with libmixed, not Harmony.

**Comment by Gleefre** [comment]
Thanks for looking into, it, I'll open an issue there then!
