### ISSUE TITLE
initialize now start?

### ISSUE THREAD

**Issue by jkcunningham** [Shirakumo/harmony#6]
Just cloned the project and was walking through your readme to understand it better. Looks like you originally initialized your server with harmony-simple:initialize but maybe changed the name to start? Initialize no longer seems to exist and start does work.

**Comment by Shinmera** [comment]
No, it's [the other way around](https://github.com/Shirakumo/harmony/blob/master/simple/default.lisp#L69). Make sure you don't have an outdated Quicklisp version lying around somewhere.

**Comment by jkcunningham** [comment]
That was it. It also picked up a dependency on libasound.so. (harmony-simple:play file.mp3 :music) no longer works though. Did that syntax change?

There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION HARMONY:PLAY (5)>
when called with arguments
  (#<HARMONY-SIMPLE:DEFAULT-SERVER running> "test1.mp3"
   #<HARMONY:BASIC-MIXER :MUSIC>).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
See also:
  Common Lisp Hyperspec, 7.6.6 [:section]
