### ISSUE TITLE
fade out at end of sound clip

### ISSUE THREAD

**Issue by jkcunningham** [Shirakumo/harmony#7]
It looks like fades are set up to occur at the beginning of a segment via time. If you wanted had, say, a 60 second clip and you wanted to fade from 0.0 up to 1.0 over the first 5 seconds, then fade from 1.0 down to 0.0 in the last 5 seconds, how would you accomplish it? And is there any way to do this if you don't know the length of the clip in advance?

Thanks.

**Comment by Shinmera** [comment]
You would need to check whether you're close enough to the end after each time `process` is called on a source.

I don't understand your second question. How would you know when the end would be if you don't know the length of it?

**Comment by jkcunningham** [comment]
Wavs would be easy. But take a compressed format - an mp3 file for example. Is there a way to query what it's length is (in seconds or decompressed samples) using the mpg123 API? If so, I could see how to set the fader to start fading out at the appropriate time. But if not, then it would probably require a call to another library which is less than optimal. 

A perhaps related issue is the sample-position method called on a mp3 source. It seems to return a non-decreasing sequence I'm guessing is total pipe samples, not position in the source. So if I call seek-to-sample on the source and set it back to 0 while it's playing, then look at it's sample-position, it's always bigger. But the position is being set back, because you can hear it start over again. The related part is: Is there a way to get position in source in samples/seconds?

**Comment by Shinmera** [comment]
All file formats I know about store the length as part of the metadata. The API for sources also includes a mandatory generic function ([`sample-count`](https://shirakumo.github.io/harmony/#HARMONY:SAMPLE-COUNT)) that returns the number of samples the source represents.

You should not call `seek-to-sample` yourself. It is only exported for extension purposes. The function [`seek`](https://shirakumo.github.io/harmony/#HARMONY:SEEK) should be used to perform actual seeking instead and will do the proper bookkeeping.

**Comment by jkcunningham** [comment]
Good to know. Thanks.
